import GlobalStyle from "@/components/GlobalStyle";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body style={{opacity: 0}}>
                <noscript>JavaScript is required for this website.</noscript>
                {children}
                <GlobalStyle/>
            </body>
        </html>
    );
}
